### ISSUE TITLE
Fava doesn't work behind AWS https proxy

### ISSUE THREAD

**Issue by jeromebaum** [beancount/fava#665] opened 2018-02-16 13:15 UTC
When I use fava in cloud9, url_for seems to return a http scheme, even if fava is sitting behind a proxy. The following snippet should fix this:

```python
from werkzeug.contrib.fixers import ProxyFix
app = Flask(__name__)

app.wsgi_app = ProxyFix(app.wsgi_app)
```

From https://stackoverflow.com/a/45333882

**Comment by yagebu** [comment] 2018-02-20 22:20
The above snippet should only be used when running behind a proxy - so this should be solved by deploying Fava differently I think. You can write an WSGI app that uses your snippet (see also https://beancount.github.io/fava/development.html#module-fava.application) and use that to run Fava.

**Comment by jeromebaum** [comment] 2018-02-21 18:06
Oh, is the reason this one?

> Do not use this middleware in non-proxy setups for security reasons.

Is this purely a security concern, or are you saying Fava would stop working with this change if you run it without a proxy? I have no way to run without a proxy so I can't check. This concern just means someone can impersonate which host they are connecting from, right? But that person would already have full access to Fava anyway, because Fava doesn't do authentication, right?

Anyway do you think it's possible to maybe hide this behaviour behind an optional switch, e.g. `--proxy-mode` or something? Looks like a few people have this problem, and a command line switch is probably better usability.

I kind of imagine the normal use-case to be "quickly spin up an instance of Fava on the command line, on-demand whenever you use it"? That's at least how I'm using it.

**Comment by xentac** [comment] 2018-02-21 18:52
I'm a bit confused because I use fava behind the oauth2_proxy and don't
have to do anything special about url schemes. I'm curious how these setups
differ. I'm probably just doing something wrong but I don't know what it is.

**Comment by yagebu** [comment] 2018-02-24 00:58
http://flask.pocoo.org/docs/0.12/deploying/wsgi-standalone/#proxy-setups might help. This seems to be something that can be fixed by configuring the proxy server to pass the right header. If it's not possible to configure your proxy server, then see my suggestion above.

> I kind of imagine the normal use-case to be "quickly spin up an instance of Fava on the command line, on-demand whenever you use it"? That's at least how I'm using it.

Yes that is what the CLI is intended for. I don't really want to encourage people to expose it on the web - for that a proper WSGI server should be used IMHO.

**Comment by yagebu** [comment] 2018-03-18 16:30
Since most proxy setups seem to work without this hack, I'll close this issue

**Closed by yagebu** 2018-03-18 16:30 UTC
Labels: deployment

**Comment by ljani** [comment] 2019-10-22 19:16
I'm proxying `fava` to get `https` support. To make this work with `traefik@2`, I had to add [a `headers` middleware](https://docs.traefik.io/middlewares/headers/) with [`sslProxyHeaders`](https://docs.traefik.io/middlewares/headers/#sslproxyheaders) set to `X-Forwarded-Proto=https`. Otherwise `fava` would redirect me back to `http` instead of `https` if I navigated to the root (ie. not `https://host/beancount/income_statement/`).

**Comment by ngoonee** [comment] 2020-07-26 06:16
@ljani I'm trying to do that (configuring via labels) and can't seem to get it to work properly.

I'm using the following labels on my fava docker container:-

    - traefik.http.middlewares.https-security.headers.sslProxyHeaders.X-Forwarded-Proto=https
    - traefik.http.routers.fava-web.middlewares=https-security

Anything else that I missed?

**Comment by ljani** [comment] 2020-07-26 18:04
I'm not sure about the Docker syntax, here's mine using TOML:

```toml
[http.middlewares.set-forwarded-proto.headers.sslProxyHeaders]
X-Forwarded-Proto = "https"

[http.routers.fava]
entryPoints = ["websecure"]
middlewares = ["set-forwarded-proto"]
rule = "Host(`fava.example.com`)"
service = "fava"
```

**Comment by ngoonee** [comment] 2020-07-27 08:00
> I'm not sure about the Docker syntax, here's mine using TOML:
> 
> ```toml
> [http.middlewares.set-forwarded-proto.headers.sslProxyHeaders]
> X-Forwarded-Proto = "https"
> 
> [http.routers.fava]
> entryPoints = ["websecure"]
> middlewares = ["set-forwarded-proto"]
> rule = "Host(`fava.example.com`)"
> service = "fava"
> ```

Looks just about exactly what I'm doing. Fava works mostly but my queries return something odd. Do you use queries, and if so do they work fine for you?

**Comment by ljani** [comment] 2020-07-27 09:21
Yes, I use queries. They work fine if I run them from the query page, but my queries in quick links are broken indeed. I always thought it was because I upgraded Fava and I haven't bothered to resolve the issue. Let me know, if you solve the problem.

**Comment by ngoonee** [comment] 2020-07-28 01:48
Ah, wonder why then. Could you check your web developer console to see what's the error (I'm getting mixed-content errors due to http being requested instead of https).

Weird thing is it worked (and still works) on my previous nginx config, there's something I'm missing in traefik that was done by nginx....

**Comment by ljani** [comment] 2020-07-31 18:48
I do not see any mixed-content, or any errors in fact in Firefox. I see a call to `/beancount/query/?partial=true` which seems to contain the query history (without the results of the queries), ie. as if I only navigated to `/beancount/query/`. I should update Fava to the latest version to debug this further.

**Comment by ljani** [comment] 2020-08-04 09:30
@ngoonee I upgraded my Fava installation and the problem is gone, queries work very well now.
