### ISSUE TITLE
Aggregate Query Using Open Meta Throws KeyError When Attempting to Filter By Time

### ISSUE THREAD

**Issue by ptrckbkr** [beancount/fava#1029] opened 2020-01-05 00:10 UTC
**1. Execute The Following Query:**
SELECT any_meta('tax') as tax, SUM(position) WHERE getitem(open_meta(account),'tax') != 'false'

**2. Then Filter By Year**

**RESULT**
Traceback (most recent call last):
  File "<REMOVED>python\python37\Lib\cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'QueryShell' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\sources\finances\.venv\lib\site-packages\beancount\query\shell.py", line 271, in run_parser
    self.dispatch(statement)
  File "d:\sources\finances\.venv\lib\site-packages\beancount\query\shell.py", line 251, in dispatch
    return method(statement)
  File "d:\sources\finances\.venv\lib\site-packages\fava\core\query_shell.py", line 89, in on_Select
    self.options_map)
  File "d:\sources\finances\.venv\lib\site-packages\beancount\query\query_execute.py", line 316, in execute_query
    if c_where is None or c_where(context):
  File "d:\sources\finances\.venv\lib\site-packages\beancount\query\query_compile.py", line 103, in __call__
    return self.operator(self.operand(context))
  File "d:\sources\finances\.venv\lib\site-packages\beancount\query\query_compile.py", line 121, in __call__
    return self.operator(self.left(context), self.right(context))
  File "d:\sources\finances\.venv\lib\site-packages\beancount\query\query_env.py", line 656, in __call__
    args = self.eval_args(context)
  File "d:\sources\finances\.venv\lib\site-packages\beancount\query\query_compile.py", line 267, in eval_args
    for operand in self.operands]
  File "d:\sources\finances\.venv\lib\site-packages\beancount\query\query_compile.py", line 267, in <listcomp>
    for operand in self.operands]
  File "d:\sources\finances\.venv\lib\site-packages\beancount\query\query_env.py", line 383, in __call__
    open_entry, _ = context.open_close_map[args[0]]
KeyError: 'Equity:Opening-Balances

**Comment by yagebu** [comment] 2020-01-10 15:25
I can't reproduce this. In any case, this looks more like a Beancount than a Fava bug.

**Comment by OptikSage** [comment] 2020-01-10 21:40
Hmm. I synced everything to the latest and now I am seeing completely different behavior. Now, it doesn't filter by time at all and the query defaults to a collapsed state. I'm rebuilding my environment and will have to try and narrow down what's happening here.

**versions:**
beancount    2.2.3.dev0    changeset:   4978:c21adfcd90ab
fava    1.13.dev12+g84df3df6    commit 84df3df6a5355318dec056779fa96f96f2ceea91

**Comment by yagebu** [comment] 2020-02-22 13:18
I'll close this, if you can narrow it down, feel free to reopen :)

**Closed by yagebu** 2020-02-22 13:18 UTC
Labels: bug-beancount, status:not-reproducible
