### ISSUE TITLE
Showing "Units" does not show the individual units in Balance and Income Statement

### ISSUE THREAD

**Issue by capi** [beancount/fava#1165] opened 2020-10-14 19:30 UTC
Given the following bean file, when showing "Units" in either Balance and/or Income Statement, only the EUR account shows a value. I'd have expected to have the other accounts to show "1 USD" and "1 STOCK" respectively.

```
option "operating_currency" "EUR"

2000-01-01 open Assets:EUR
2000-01-01 open Assets:USD
2000-01-01 open Assets:STOCK
2000-01-01 open Income:Test

2007-12-31 commodity EUR
  fullname: "Euro"

2007-12-31 commodity USD
  fullname: "US Dollar"

2007-12-31 commodity STOCK
  fullname: "Some Stock"

2020-10-14 * "Income EUR"
 Assets:EUR                                 1.00 EUR
 Income:Test

2020-10-14 * "Income USD"
 Assets:USD                                 1.00 USD
 Income:Test

2020-10-14 * "Income USD"
 Assets:STOCK                                  1 STOCK
 Income:Test
```

![image](https://user-images.githubusercontent.com/254852/96036249-7d802280-0e64-11eb-9082-219f6f066e08.png)

**Comment by yagebu** [comment] 2020-10-15 16:29
This is a duplicate of #1131 

I'll make a new release soon.

**Closed by yagebu** 2020-10-15 16:29 UTC
