### ISSUE TITLE
Custom queries no longer seem to work

### ISSUE THREAD

**Issue by floatingheads** [beancount/fava#1172] opened 2020-10-27 11:35 UTC
Example code:
`2020-08-26 query "Emergency Fund" "SELECT date, account, position, balance FROM OPEN ON 2020-10-09 WHERE account ~ 'Assets:*.*:EmgcyFund'"`

Error returned is "Error: NOT FOUND".

All my custom queries are generating this error as well as any query directly from fava. Everything was working fine with PyPI v1.15. Just started happening with PyPI v1.16.

**Comment by yagebu** [comment] 2020-11-01 10:20
I can't reproduce that error. Can you run fava in debug mode and see if that produces a more detailed error message?

There is another bug on the query page that I just fixed, but that would produce quite a different error message.

**Comment by floatingheads** [comment] 2020-11-02 12:44
How do I run it in debug mode?

**Comment by yagebu** [comment] 2020-11-02 20:52
`fava --debug`

**Comment by floatingheads** [comment] 2020-11-02 21:57
This is what it spit out when I ran the debug:

  ```
* Serving Flask app "fava.application" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "c:\users\williamb\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\williamb\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\williamb\AppData\Local\Programs\Python\Python38-32\Scripts\fava.exe\__main__.py", line 7, in <module>
  File "c:\users\williamb\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\williamb\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\williamb\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\williamb\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\williamb\appdata\local\programs\python\python38-32\lib\site-packages\fava\cli.py", line 102, in main
    app.run(host, port, debug)
  File "c:\users\williamb\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "c:\users\williamb\appdata\local\programs\python\python38-32\lib\site-packages\werkzeug\serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```

**Comment by floatingheads** [comment] 2020-11-02 22:02
This is what I got when running the debug and clicking the query. It didn't give me an error in the browser this time, but didn't spit out query results either.

```
* Serving Flask app "fava.application" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 270-007-037
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Nov/2020 17:00:16] "?[32mGET / HTTP/1.1?[0m" 302 -
127.0.0.1 - - [02/Nov/2020 17:00:16] "?[37mGET /bean-family-financials/income_statement/ HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:16] "?[37mGET /static/app.css?mtime=1603195260 HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:17] "?[37mGET /static/fira-sans-all-400.woff2 HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:17] "?[37mGET /static/fira-mono-all-400.woff2 HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:17] "?[37mGET /static/fira-sans-all-500.woff2 HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:17] "?[37mGET /static/app.js?mtime=1603195260 HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:17] "?[37mGET /static/favicon.ico?mtime=1603195260 HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:24] "?[37mGET /bean-family-financials/query/?query_string=run+%22Emergency+Fund%22&partial=true HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:24] "?[37mGET /static/source-code-pro-all-400.woff2 HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:25] "?[37mGET /bean-family-financials/api/query_result?query_string=run+%22Emergency+Fund%22 HTTP/1.1?[0m" 200 -
127.0.0.1 - - [02/Nov/2020 17:00:30] "?[37mGET /bean-family-financials/api/query_result?query_string=run+%22Emergency+Fund%22 HTTP/1.1?[0m" 200 -
```

**Comment by yagebu** [comment] 2020-11-03 06:52
This then sounds more like the bug that I fixed in 04c0cd79d0e99c03ba0a1bb0ca96c7c6fb66e2db. Is there an error in the browser console? (and for the sake of completeness, which browser are you using?)

**Comment by floatingheads** [comment] 2020-11-03 11:50
I'm using Chrome, but got the same problem with Microsoft Edge also.
I get this in the browser console:

```
app.js?mtime=1603195260:16206 Duplicate keyboard shortcut:  Control+Enter <button type=​"submit" class=​"svelte-1xc24s1" data-key=​"Control+Enter">​Submit​</button>​
bindKey @ app.js?mtime=1603195260:16206
keyboardShortcut @ app.js?mtime=1603195260:16225
m @ app.js?mtime=1603195260:32006
mount_component @ app.js?mtime=1603195260:1850
m @ app.js?mtime=1603195260:32678
mount_component @ app.js?mtime=1603195260:1850
init @ app.js?mtime=1603195260:1939
Query @ app.js?mtime=1603195260:32842
connectedCallback @ app.js?mtime=1603195260:32975
loadURL @ app.js?mtime=1603195260:3029
async function (async)
loadURL @ app.js?mtime=1603195260:3021
navigate @ app.js?mtime=1603195260:2995
(anonymous) @ app.js?mtime=1603195260:3094
(anonymous) @ app.js?mtime=1603195260:2685

app.js?mtime=1603195260:2125 Uncaught (in promise) Error: Expected an array: (json) => {
          try {
              return validator(json);
          }
          catch (err) {
              return value;
          }
      }
    at app.js?mtime=1603195260:2235
    at balances (app.js?mtime=1603195260:16864)
    at parseQueryChart (app.js?mtime=1603195260:17014)
    at get.then.setResult.error.error (app.js?mtime=1603195260:32772)
```

**Comment by Freezind** [comment] 2020-11-03 12:00
I have the same issue too.
```
app.js?mtime=1603117861:2235 Uncaught (in promise) Error: Expected an array: (json) => {
          try {
              return validator(json);
          }
          catch (err) {
              return value;
          }
      }
    at app.js?mtime=1603117861:2235
    at balances (app.js?mtime=1603117861:16864)
    at parseQueryChart (app.js?mtime=1603117861:17014)
    at get.then.setResult.error.error (app.js?mtime=1603117861:32772)
```
Got these errors from chrome console.

**Comment by yagebu** [comment] 2020-11-08 13:39
This is fixed by https://github.com/beancount/fava/commit/04c0cd79d0e99c03ba0a1bb0ca96c7c6fb66e2db

**Closed by yagebu** 2020-11-08 13:39 UTC
Labels: bug
