### ISSUE TITLE
Error: The file changed externally.

### ISSUE THREAD

**Issue by Singularitytf** [beancount/fava#1333] opened 2021-09-23 18:48 UTC
I cannot edit my *.beancount file through fava editor. When I tried to save the file through command+s, it will report "Error: The file changed externally.". However, it can be edited through emacs.

Platform: macOS 11.6 (M1)

**Comment by yagebu** [comment] 2021-12-04 11:01
Fava computes a checksum to ensure that we do not accidentally overwrite changes to the Beancount file that some other program did - in which case getting this error is the desired behaviour. Did you maybe edit the file in Emacs at the same time?

**Comment by yagebu** [comment] 2022-02-20 12:56
As this sounds like the intended behavior (without any reproducible steps to suggest otherwise), I'm closing this issue.

**Closed by yagebu** 2022-02-20 12:56 UTC
Labels: status:not-reproducible
