### ISSUE TITLE
Opening Balance View with Graphs Enabled Breaks Page Load

### ISSUE THREAD

**Issue by amoskyler** [beancount/fava#808] opened 2018-08-29 03:43 UTC
I'm not sure how to provide specific debugging information on this issue, and I also don't know how to reproduce it with minimal transactions. I will do my best do describe the issue, and am happy to go through any additional debugging steps which will provide extra details.

I have an account `Assets:US:Trading:Cash` which when loaded in fava causes the page to freeze/crash. I believe the issue is related to graph rendering as the page loads fine when `?charts=false` is set on the URI.

In this case the URI which fails is `http://localhost:5000/finances/account/Assets:US:Trading:Cash`. This occurs no matter how I load the page, as long as charts are enabled.

I should also mention this occurs when loading the parent account `Assets:US:Trading` as well. Oddly enough, it does not appear to impact `Assets:US`.

Any ideas what could cause this? How can I get further debugging information on the hangup the chart is encountering?

Thanks!

**Comment by yagebu** [comment] 2018-08-29 07:13
Thanks for reporting this!

Which browser (and version) are you using? Can you open the browser console (part of what's usually called "developer tools" or something) and see if any errors show up when you load the page?

**Comment by amoskyler** [comment] 2018-08-29 08:10
Sure thing!

I've tested the issue in both Chrome and Firefox.  Current Chrome version is 68.0.3440.106 and Firefox version is 60.0.1  (64 bit).

I've attempted to take a heap dump from Chrome's Dev tools when loading the page with no success. The heap dump doesn't complete, and the page completely freezes.

**Comment by yagebu** [comment] 2018-08-29 22:01
It could be that this is the same as #802 - are you using the stable version or the git master branch?

**Comment by amoskyler** [comment] 2018-08-30 03:59
Alright, it does appear to be a similar (if not identical!) issue. I've been using the stable 1.8, so I went ahead and built from master to test and was able to determine the issue is resolved in Firefox. The issue is still present in Chrome however.

**Comment by yagebu** [comment] 2018-08-30 09:00
Thanks for investigating - can you try to see if you can reproduce this with one of the example files?

**Comment by yagebu** [comment] 2018-09-02 07:29
I've bumped some of the JS dependencies again, could you check if this is fixed now?

**Comment by dholl** [comment] 2018-09-27 04:49
I'm experiencing the same issue with 2 of my 6 ledgers in both Safari 12.0 and Firefox 62.0.2.

In Firefox, I eventually get a message asking "A web page is slowing down your browser.  What would you like to do?" with options of either "Stop It" or "Wait".
<img width="632" alt="image" src="https://user-images.githubusercontent.com/4298582/46123327-9a405380-c1d2-11e8-9f7d-e3790b9b41fb.png">
If I click "Stop It", then the chart seems to load okay, but "fava-option" "auto-reload" "True" seems non-functional then.

This only happens on 2 of my 6 ledgers.  One of the ledgers used to be fine, perhaps up to a month or two ago (?)...  so perhaps there's hope I can narrow it down.

Do you have any guidance for diagnostics I might try in Firefox?  So far, if I enable "Web Console" under Developer Tools, the console is empty while loading the page, but when I finally press "Stop It", I get this text:
```
Error: Script terminated by timeout at:                                  app.js:20590:12
Voronoi@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:20590:12
voronoi@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:20929:11
update@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:22745:23
draw@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:22713:6
renderers[id]@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:23012:50
show@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:22942:24
update@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:22929:8
reset@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:22919:6
@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:23105:4
trigger/<@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:438:6
trigger@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:437:4
loadURL/</<@https://mydomain.org/bean/static/gen/app.js?mtime=1532846841:14168:12
```
(Note: ```mydomain.org/bean``` is a placeholder.  -- I monkey-patched my fava installation to add user authentication and ledger-level user authorization.)

I installed beancount and fava via ```pip install --no-cache-dir --upgrade --quiet pip beancount fava``` --- which is also rerun weekly via a cron job to check for updates.

**Comment by yagebu** [comment] 2018-10-08 16:39
Have you tried running from the development version (this is still broken in the released version, since there has been no release since the potential fix)

**Closed** 2018-10-08 19:17 UTC
Labels: bug, bug-external
