### ISSUE TITLE
The chart don't display in 1.22

### ISSUE THREAD

**Issue by charlieshen7** [beancount/fava#1446] opened 2022-07-09 06:24 UTC
Everything works fine in fava1.21
but when i update fava to 1.22, the chart can't display in the webpage

And i also can't see the filter option; journal content
If i reinstall fava 1.21, everything works fine( chart, filters .etc)

should i change some option to make fava 1.22 works well?

beancount version is 2.3.4
python version is 3.9.7

**Comment by kba977** [comment] 2022-07-10 15:20
I hava the same question.

beancount: 2.3.5
python: 3.8.13

**Comment by adrienbeau** [comment] 2022-07-14 21:43
I came here to report the same problem. A very significant regression, the title of the issue does not reflect how much Fava is broken right now for me. No journal content, no chart, no filter...

This is using the latest (as of writing) Beancount 2.3.5+ (commit b82fc257b2e1ad07784c95e68f8df76df980d3a2) and Fava 1.22.1, with Python 3.8.10.

Most importantly perhaps, Firefox 102.0 on Ubuntu 20.04, with few extensions (KeePassXC-Browser, Plasma Integration, uBlock Origin). In particular, turning off uBlock Origin does not change anything (it was not blocking anything on localhost anyway). Force reloading does not solve the issue either.

The console is chock full of errors, starting with a very suspicious "Uncaught Error: Loading ledger data failed.", followed by many "Uncaught TypeError: val is undefined", and then a lot of 404 errors trying to `GET http://localhost:5000/my-personal-beancount-file/income_statement/undefinedapi/changed`.

**Comment by adrienbeau** [comment] 2022-07-14 22:13
I did a quick `git bisect` before calling it off for the night. Actually two, because the charts and journal break in separate commits.

* 233d30a566eda37bfd36877246e2844098da63c8 is the first bad commit. It breaks the charts, however the journal keeps working.
* 16cdcd4230342cc2268422e4e170d41aac29ab14 is the first commit that breaks the journal.

**Comment by adrienbeau** [comment] 2022-07-15 10:07
As I investigate this further, I notice I have not properly followed the build instructions, so my comments above are incorrect, because `app.js` was not properly regenerated.

Installing the released egg using `pip install --upgrade fava` gives me a version that works fine.

**Comment by charlieshen7** [comment] 2022-07-28 11:50
> I can't reproduce this. Have you force-reloaded the browser to ensure you don't have outdated cached frontend code running? Are there errors on the Javascript console? Does this also happen with a trivial sample file? If so, can you provide one?

![image](https://user-images.githubusercontent.com/31721151/181497574-387d7607-552a-4824-8f21-3a96f4e9e3c8.png)
here is an error

I tried force-reloaded the browser and used the sample file, but didn't work, the chart can't show up in 1.22 still

**Comment by yagebu** [comment] 2022-07-29 21:02
Seems like the mimetype guessing on your machine is broken. Are you on Windows by any chance? Can you check whether your registry is properly configured? see https://github.com/pallets/flask/issues/1045 for more details about this

**Comment by charlieshen7** [comment] 2022-08-01 06:30
> Seems like the mimetype guessing on your machine is broken. Are you on Windows by any chance? Can you check whether your registry is properly configured? see [pallets/flask#1045](https://github.com/pallets/flask/issues/1045) for more details about this

Do you mean this registry? It seems nothing wrong
![image](https://user-images.githubusercontent.com/31721151/182086076-cdb49519-d48f-405f-bec4-857da81c8157.png)

**Comment by charlieshen7** [comment] 2022-08-01 06:31
> Seems like the mimetype guessing on your machine is broken. Are you on Windows by any chance? Can you check whether your registry is properly configured? see [pallets/flask#1045](https://github.com/pallets/flask/issues/1045) for more details about this

Do you mean this registry? It seems nothing wrong
![image](https://user-images.githubusercontent.com/31721151/182086076-cdb49519-d48f-405f-bec4-857da81c8157.png)

**Comment by charlieshen7** [comment] 2022-08-01 06:31
> Seems like the mimetype guessing on your machine is broken. Are you on Windows by any chance? Can you check whether your registry is properly configured? see [pallets/flask#1045](https://github.com/pallets/flask/issues/1045) for more details about this

Do you mean this registry? It seems nothing wrong
![image](https://user-images.githubusercontent.com/31721151/182086076-cdb49519-d48f-405f-bec4-857da81c8157.png)

**Comment by ThomasdenH** [comment] 2022-08-11 10:20
I have an issue with `1.22.3` that may be related. I'm on Windows as well (although I run Fava through WSL). The issue happens independently of browser.

![image](https://user-images.githubusercontent.com/3889750/184112666-61ea7223-a1d5-4327-bbb7-f2f55a137e57.png)
![image](https://user-images.githubusercontent.com/3889750/184112587-b753a2a8-4004-431f-b6ee-68274f33e2f7.png)
![image](https://user-images.githubusercontent.com/3889750/184112520-1043c0d0-21f4-4e0f-9050-6e81e36c4a17.png)

FWIW,
```python
import mimetypes

print(mimetypes.guess_type('style.css'))
```

outputs `('text/css', None)` as expected.

**Comment by CicadaCinema** [comment] 2022-08-28 15:28
I am also experiencing this issue:
![image](https://user-images.githubusercontent.com/52425971/187081380-cbb81080-ff91-46e0-b76a-c9bd3f556cdc.png)

## Resolution

The problem was resolved after changing value of the "Content Type" registry entry visible in the screenshot above to "text/javascript" and rebooting my computer.

## Version information:
```
C:\Users\Atom>bean-check --version
Beancount 2.3.5

C:\Users\Atom>fava --version
fava, version 1.22.3

C:\Users\Atom>python --version
Python 3.10.1
```

![image](https://user-images.githubusercontent.com/52425971/187081567-bad231b6-1e81-4c51-bb8d-cf58d1c99d69.png)

## Other reports of this problem

https://github.com/golang/go/issues/32350
https://developercommunity.visualstudio.com/t/installer-mime-type-for-js-extension-is-set-to-tex/954263

**Comment by yagebu** [comment] 2022-09-28 15:50
I'm closing this issue - this seems to be a Windows problem and not a Fava issue IMHO

**Closed by yagebu** 2022-09-28 15:50 UTC
Labels: platform:windows, bug-external

**Comment by charlieshen7** [comment] 2022-10-07 15:23
> I am also experiencing this issue: ![image](https://user-images.githubusercontent.com/52425971/187081380-cbb81080-ff91-46e0-b76a-c9bd3f556cdc.png)
> 
> ## Resolution
> The problem was resolved after changing value of the "Content Type" registry entry visible in the screenshot above to "text/javascript" and rebooting my computer. It may be necessary to reload your browser cache to fix this issue.
> 
> ## Version information:
> ```
> C:\Users\Atom>bean-check --version
> Beancount 2.3.5
> 
> C:\Users\Atom>fava --version
> fava, version 1.22.3
> 
> C:\Users\Atom>python --version
> Python 3.10.1
> ```
> 
> ![image](https://user-images.githubusercontent.com/52425971/187081567-bad231b6-1e81-4c51-bb8d-cf58d1c99d69.png)
> 
> ## Other reports of this problem
> [golang/go#32350](https://github.com/golang/go/issues/32350) https://developercommunity.visualstudio.com/t/installer-mime-type-for-js-extension-is-set-to-tex/954263

thanks a lot!
