### ISSUE TITLE
Currency conversion select

### ISSUE THREAD

**Issue by ibigbug** [beancount/fava#1436] opened 2022-07-02 19:50 UTC
The current logic check if the val is an ISO currency: https://github.com/beancount/fava/blob/6ec42909454a882c70fec8097e72ff7071edd10c/frontend/src/stores/chart.ts#L37

This becomes interesting when a stock symbol is also a currency symbol:

https://github.com/beancount/fava/blob/6ec42909454a882c70fec8097e72ff7071edd10c/frontend/src/lib/iso4217.ts#L112
https://finance.yahoo.com/quote/NIO/

So `NIO` will show up in the conversion select:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/543405/177014488-de5c5f69-97d6-44ff-bfe0-396dafdc08d5.png">

But it's not a "currency" in my current bookkeeping, but a stock that I hold.

Any ideas to hide the "stock" in the "currency" list?

**Comment by yagebu** [comment] 2022-07-03 18:37
This is a duplicate of #1226

**Closed by yagebu** 2022-07-03 18:37 UTC
Labels: duplicate
