### ISSUE TITLE
regex filters don't work in Safari

### ISSUE THREAD

**Issue by dustinfarris** [beancount/fava#1117] opened 2020-05-29 17:37 UTC
If I type in an account filter, like `.*Consulting.*` and press enter in Safari, nothing changes.  But it works in Firefox.

**Comment by yagebu** [comment] 2020-05-30 08:26
This sounds like a duplicate of #1098

**Closed** 2020-06-07 10:01 UTC
Labels: duplicate

**Comment by dustinfarris** [comment] 2020-06-07 11:58
Why is this being closed?  As far as I can tell, this is still not fixed.

**Comment by yagebu** [comment] 2020-06-07 15:17
> Why is this being closed?

It's a duplicate.

Also, this should be fixed now, since the filters are now also applied when focus leaves the input.

**Comment by dustinfarris** [comment] 2020-06-07 16:02
> Also, this should be fixed now, since the filters are now also applied when focus leaves the input.

It is not fixed for me.  pressing enter does not apply the filter.  blur (losing focus) does not apply the filter.

**Comment by dustinfarris** [comment] 2020-06-07 16:16
> > Also, this should be fixed now, since the filters are now also applied when focus leaves the input.
> 
> It is not fixed for me. pressing enter does not apply the filter. blur (losing focus) does not apply the filter.

nvm, I just upgraded to the latest fave and blur seems to work now.
