### ISSUE TITLE
Mobile widths don't automatically hide the side menu anymore

### ISSUE THREAD

**Issue by xentac** [beancount/fava#972] opened 2019-09-24 17:05 UTC
It seems like the order of the CSS has been changed so the mobile top and margin values are always superceded by the desktop values. I believe this is why most devs write the defaults as mobile and then progressively override them with larger values instead of writing desktop values and then trying to override with mobile values.

In addition the ... button to expose and hide the side menu is now just the + button for adding new transactions.

**Comment by yagebu** [comment] 2019-09-24 17:28
Can't reproduce this

**Comment by xentac** [comment] 2019-09-24 19:15
![Mobile widths](https://user-images.githubusercontent.com/1805/65542653-6a4e8d80-dec4-11e9-8d14-79934d5b3858.png)

It looks like the @media section is on line 1177 and the default aside is on 1928.

I just rebuilt using v1.11-19-gf7ad2f7 of fava.

**Comment by yagebu** [comment] 2019-09-24 19:32
Building the same commit, I get them in the correct order (as they also are in the source code). Could you try debugging what could go wrong with the build process on your machine?

**Comment by xentac** [comment] 2019-09-24 22:57
This is my Dockerfile. It doesn't seem to be in sync with the most recent Dockerfile updates (specifically https://github.com/beancount/fava/commit/c6199f8307f549f30d50569515e3fbd8d4e5d094#diff-17cf6e2f8ffdc014050de54a72876254) but have there been any updates in the instructions on how to build from source?

$ cat Dockerfile
FROM python:3.6.8-alpine

ENV BEANCOUNT_INPUT_FILE ""
ENV FAVA_OPTIONS "-H 0.0.0.0"
ENV FINGERPRINT "fingerprints=sha256:4e:65:3e:76:0f:81:59:85:5b:50:06:0c:c2:4d:3c:56:53:8b:83:3e:9b:fa:55:26:98:9a:ca:e2:25:03:92:47"
ENV BUILDDEPS "libxml2-dev libxslt-dev gcc musl-dev mercurial git nodejs nodejs-npm make g++"
ENV RUNDEPS "libxml2 libxslt cython"

ARG beancount_hash
ARG fava_hash
ARG build_month

RUN cd /root \
        && python3 -mpip install --upgrade pip \
        && apk upgrade --update \
        && apk add --update $BUILDDEPS $RUNDEPS \
        && mkdir /packages #$build_month
# Remove the .hg directory because of pip install /tmp copytree Operation not supported errors
RUN hg clone --config hostsecurity.bitbucket.org=$FINGERPRINT https://bitbucket.org/blais/beancount \
        && (cd beancount && hg log -l1 && hg log -r . --template '{latesttag}-{latesttagdistance}-{node|short}\n' > /beancount-ref) \
        && (cd beancount && python3 setup.py bdist_wheel --universal && mv dist/*.whl /packages ) \
        && python3 -mpip install ./beancount \
        && rm -r beancount #$beancount_hash
RUN git clone https://github.com/beancount/fava.git \
        && (cd fava && git log -1 && git describe --tags > /fava-ref) \
        && make -C fava \
        && make -C fava mostlyclean \
        && rm fava/docs/changelog.rst \
        && (cd fava && python3 setup.py bdist_wheel --universal && mv dist/*.whl /packages) \
        && python3 -mpip install ./fava \
        && rm -r fava #$fava_hash
RUN git clone https://github.com/xentac/beancount-plugins-xentac.git \
        && (cd beancount-plugins-xentac && python3 setup.py bdist_wheel --universal && mv dist/*.whl /packages) \
        && python3 -mpip install ./beancount-plugins-xentac \
        && rm -r beancount-plugins-xentac
RUN git clone https://github.com/hoostus/beancount-price-sources.git \
        && python3 -mpip install ./beancount-price-sources \
        && rm -r beancount-price-sources
#RUN python3 -mpip uninstall --yes pip \
RUN \
        find /usr/local/lib/python3.6/site-packages -name *.so -print0|xargs --no-run-if-empty -0 strip -v \
        && apk del $BUILDDEPS \
        && rm -rf /var/cache/apk/* /var/cache/apk/.[!.]* /tmp/* /tmp/.[!.]* /root/* /root/.[!.]* \
        && find /usr/local/lib/python3.6 -name __pycache__ -print0|xargs -0 rm -rf \
        && find /usr/local/lib/python3.6 -name *.pyc -print0|xargs -0 rm -f

# Default fava port number
EXPOSE 5000

CMD fava $FAVA_OPTIONS $BEANCOUNT_INPUT_FILE

**Comment by yagebu** [comment] 2019-09-25 15:01
> but have there been any updates in the instructions on how to build from source?

Not really.

**Comment by xentac** [comment] 2019-09-30 22:31
Looking a little deeper and comparing fava.pythonanywhere.com to my own css file, it looks like the problem is that the CSS files are combined using https://www.npmjs.com/package/rollup-plugin-css-only in a different order. My base.css ends up being merged into app.css after media-mobile.css.

Having the order that CSS is in the file affect whether or not mobile looks right kind of sucks. I don't have control over the order that rollup-plugin-css-only merges the files.

Looking online there are a couple of options for how to deal with this, but none of them seems perfect:
1. The more specific CSS always wins, so if everything inside an @media has a "body" tag prepended, it will always be more specific than the non-body version.
2. Every value inside an @media could be !important, but that can make debugging/inline overriding harder
3. Every value that's overridden in the media-mobile.css file could have its desktop counterpart also listed (e.g. "top" and "margin left" could be defined in (max-width: 767px) and (min-width: 768px) varieties).

See https://stackoverflow.com/questions/45568947/override-styles-in-media-queries-with-custom-css and https://stackoverflow.com/questions/19038240/media-query-styles-not-overriding-original-styles

**Comment by xentac** [comment] 2019-10-01 19:55
A preliminary test seems to show that switching to rollup-plugin-css-bundle from rollup-plugin-css-only preserves the module import order in the generated CSS and does what we want.

**Comment by yagebu** [comment] 2019-10-03 19:11
Which version of Node do you use? For me rollup-plugin-css-only outputs the styles in the correct order. As far as I can tell, it relies on Javascript object insertion order, which is part of ES2015. The rollup-plugin-css-bundle plugin doesn't support rollup 1, so that's not really an option.

**Comment by yagebu** [comment] 2019-11-22 17:20
Closing due to lack of reproduction and the fact that it doesn't concern released versions.

**Closed by yagebu** 2019-11-22 17:20 UTC
Labels: bug, status:not-reproducible
