### ISSUE TITLE
Show Expense/Income over time with category color

### ISSUE THREAD

**Issue by johan456789** [beancount/fava#1156] opened 2020-09-15 09:44 UTC
This is a feature in GNUCash and I think this will be a good addition to fava.

![gnucash](https://web.archive.org/web/20190601140328if_/https://island.shaform.com/images/2018/12/expense.png)

Currently fava shows the total amount only.

![fava](https://i.imgur.com/XKoACi0.jpg)

Fava already shows treemap with different color for main categories, so it seems that this feature is not too hard to add?

![treemap](https://i.imgur.com/QbkzCn0.jpg)

**Comment by yagebu** [comment] 2020-09-27 10:19
Duplicate of #716

**Closed by yagebu** 2020-09-27 10:19 UTC
