### ISSUE TITLE
Key/value pairs as labels

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#486] opened 2017-01-25 04:41 UTC
This is a very low priority feature request. I see my key/value pairs showing up as labels:

![image](https://cloud.githubusercontent.com/assets/691755/22277911/4d6ad8c6-e274-11e6-97d8-cc433a14ce8b.png)

This is great. Could the hover text on these labels be made to show the key/value pair? Thanks!

**Comment by aumayr** [comment] 2017-01-25 07:20
This should already be implemented here: https://github.com/beancount/fava/blob/master/fava/templates/_journal_table.html#L220

Are you running on `master`?

**Comment by yagebu** [comment] 2017-01-25 15:29
Duplicate of #455. And already implemented.

**Closed by yagebu** 2017-01-25 15:29 UTC
Labels: duplicate

**Comment by redstreet** [comment] 2017-01-25 16:07
Thanks @aumayr. I'm behind master, which explains.
