### ISSUE TITLE
Missing requirements for "readline"

### ISSUE THREAD

**Issue by xorange** [beancount/fava#525] opened 2017-04-13 11:22 UTC
I'm installing on a machine which has no access to Internet, so I have to manually install all the dependencies.

I ran "sudo python3 setup.py install" in fava 1.3 and succeeded, but got an error of missing "readline".
I fixed it by installing it.

So...Turns out fava 1.3 requires "readline", which is absent from the pypi requirement. Suggest you add it.

Regards~

**Comment by yagebu** [comment] 2017-04-13 14:06
`readline` is part of the Python Standard Library so it should come with your Python installation. How did you install Python?

If you're on Windows, this is a duplicate of #508 (and should be fixed).

**Closed** 2017-04-17 12:50 UTC
Labels: invalid

**Comment by senorsmile** [comment] 2017-11-22 06:18
I had the same error trying to install fava in a fresh pyenv.  It would seem there are multiple packages not present.  

Luckily, ubuntu 16.04 does come with python3 now... so the following installs it correctly:
```
sudo easy_install pip3
sudo pip3 install fava
```
