### ISSUE TITLE
Autocompletion disregards previous text

### ISSUE THREAD

**Issue by tbm** [beancount/fava#714] opened 2018-03-27 19:04 UTC
* Write `payee:` in the filter box and autocompletion shows payee: entries.
* Now click somewhere outside of the filter box
* Click the filter box again
* Even though it says `payee:`, it now shows all tags.

Is there a way to take the existing text into account?  Now that I didn't put a space after payee:.

In fact, when I click the filter box again, I don't think any autocompletion should be shown at all. Only when I type another character.

**Comment by tbm** [comment] 2018-03-27 22:30
> Only when I type another character.

Just to clarify: what I wrote only applies if there's text in the filter box already.

If it's empty, of course clicking should bring up the autocompletion menu.

**Comment by yagebu** [comment] 2018-03-28 14:20
This only happens if you insert the cursor before `payee:` in which case the current behaviour is correct I think. But then moving the cursor doesn't change the completions, so that should be fixed.

> In fact, when I click the filter box again, I don't think any autocompletion should be shown at all. Only when I type another character.

I disagree

**Comment by tbm** [comment] 2018-04-07 08:28
Sorry, I didn't see your reply.

>  This only happens if you insert the cursor before payee: in which case the current behaviour is correct

No, if I write "payee", stop, click outside, click back *at the end of* payee then I see tags.  See the picture:

![payee](https://user-images.githubusercontent.com/1556037/38452957-4e7c3e48-3a4e-11e8-886c-e0be783e48e8.png)

**Comment by yagebu** [comment] 2018-04-13 13:55
Works in Firefox as expected, but as you pointed out, it doesn't in Chromium

**Comment by tbm** [comment] 2018-04-13 17:59
> Works in Firefox as expected, but as you pointed out, it doesn't in Chromium

I didn't notice that but you're right. Works in Firefox, doesn't work in Chromium.

**Comment by yagebu** [comment] 2018-04-14 10:42
This seems to be a bug in Chromium - after reentering the input, `input.selectionStart` reports `0` independently of the actual cursor position.

**Comment by yagebu** [comment] 2018-04-20 11:33
I'll close this since it's a browser bug and not a bug in Fava (and I don't see how to work around it). You might want to report this to Chromium if it still bugs you.

**Closed by yagebu** 2018-04-20 11:33 UTC
Labels: bug
