### ISSUE TITLE
AttributeError with flask-babel 3

### ISSUE THREAD

**Issue by AlphaJack** [beancount/fava#1549] opened 2023-02-20 01:05 UTC
flask-babel reached a new major version which contains breaking changes: https://github.com/python-babel/flask-babel/releases/tag/v3.0.0

If Fava is launched with this flask-babel version, the following error appears:

```python
Traceback (most recent call last):
  File "/usr/bin/fava", line 5, in <module>
    from fava.cli import main
  File "/usr/lib/python3.10/site-packages/fava/cli.py", line 13, in <module>
    from fava.application import app
  File "/usr/lib/python3.10/site-packages/fava/application.py", line 152, in <module>
    BABEL.localeselector(get_locale)
AttributeError: 'Babel' object has no attribute 'localeselector'
```

A workaround is reverting to flask-babel 2, released in 2020

**Comment by ethhics** [comment] 2023-02-21 01:34
Yep, just ran into this too. And it's tax time…argh.

Per https://github.com/python-babel/flask-babel/issues/107#issuecomment-1384548987, it seems like you need a super minor change in order to add support. Let me see if I can't make a pull request for it real quick.

**Comment by ethhics** [comment] 2023-02-21 02:19
I'll note that the [`setup.cfg`](
https://github.com/beancount/fava/blob/main/setup.cfg#L52) specifies that Flask-Babel must be less than version 3, so theoretically this should not be an issue. However, I ran into the same issue you had because the Arch `fava` AUR package didn't work anymore following a system upgrade, and wouldn't you know:

```
$ pacman -Ss python-flask-babel
community/python-flask-babel 3.0.1-1 [installed]
    Adds i18n/l10n support to Flask applications with the help of the Babel library.
```

So, if this mirrors your problem, then we'll probably need to update the `PKGBUILD` on the Arch side as well to pin it to fava's supported version range—at least until the PR gets approved to upgrade to v3.

**Comment by yagebu** [comment] 2023-02-21 17:05
Fixed in d61295cb090307c545d16a26dc96391b9afb7cb1

**Closed by yagebu** 2023-02-21 17:05 UTC

**Comment by Donearm** [comment] 2023-02-24 16:58
It doesn't seem to be fixed at least not for me. Same error, on Archlinux, with fava 1.24 and python-flask-babel 3.0.1

Already tried removing both packages and dependencies, downloading fresh ones and installed them to no avail.

**Comment by AlphaJack** [comment] 2023-02-24 17:36
> It doesn't seem to be fixed at least not for me. Same error, on Archlinux, with fava 1.24 and python-flask-babel 3.0.1

Same setup as you, on mine it works 🤔

**Comment by Donearm** [comment] 2023-02-25 10:50
As the adage goes, the issue is often between the chair and the screen :)

Removed a 1.23 version of fava installed under .local through pip who knows how many months ago. All good now.
