### ISSUE TITLE
Incorrect price dates are used for interval charts.

### ISSUE THREAD

**Issue by molikto** [beancount/fava#1101] opened 2020-05-13 16:25 UTC
<img width="1435" alt="Screen Shot 2020-05-14 at 00 18 36" src="https://user-images.githubusercontent.com/1373829/81838310-8a78ad00-9578-11ea-82e8-2fe7fb95c34c.png">

Confusing:
Change the date range changes the data in the report (7 and 9), but not the data in the chart (always 7)

-------

If you change the price on 06-02 to 06-01, then it is used in the report for month 05.

<img width="921" alt="Screen Shot 2020-05-14 at 00 07 25" src="https://user-images.githubusercontent.com/1373829/81838547-d75c8380-9578-11ea-8f16-9b59bb739287.png">

**Comment by yagebu** [comment] 2020-05-14 16:25
The first example works as expected (and I think the current behaviour is sensible): By default, the latest price is used for conversions except for places where we have a date to do the conversion on. So for example for the interval charts, we have the end dates of the interval as canonical conversion dates and in the Journal, the transaction dates are used.

The second one is a bug. The intervals in Beancount all have exclusive end dates, but for the conversion we need to use the inclusive end dates. For the net worth chart, this was already addressed in #973

**Comment by jitinl** [comment] 2020-05-14 21:16
I have a similar issue:

As an example consider the following entry 

```
2017-01-01      *       "transaction"
        Income:Sales    10 USD @ 1.2 CAD
        Assets:Savings

2017-01-02 price USD 1.5 CAD
```

In Fava, the assets would (correctly) show as 12 CAD, but the income statement would show sales and net profit of 15 CAD in the "Converted to CAD" mode. The two reports - assets and income do not balance with themselves. I think that since the conversion value has been explicitly specified in the posting, that should be considered by Fava instead of the latest conversion value. 

If I have 100 USD in my bank account (Asset), their value in terms of CAD will keep on changing every month and so the latest conversion value should be used - that makes sense. But if I made a sale (Income) of 100 USD and realised the proceedings in CAD with the exchange rate that I specified, then I think the conversion should be made with that exchange rate and not with the latest available rate.

**Comment by jitinl** [comment] 2020-05-14 22:05
Further, I think it is wrong to use the latest price for conversions for income and expense accounts at all.

Let's say you are a Canadian company that made a sale of 1 million USD and deposited it to your Canadian account when the prevailing rate was 1 USD = 1.2 CAD, hence getting 1.2 million CAD in your account. At the end of the year when you make your annual report, the prevailing rate has increased to 1 USD = 1.5 CAD. Fava would show your annual sales as 1.5 million CAD instead of 1.2 million CAD. That is clearly incorrect and you wouldn't show 1.5 million CAD in your annual income report or tax returns when you made only 1.2 million CAD. 

Let's take another example where you are the same Canadian company and you again make a sale of 1 million USD but this time deposit it to a US bank account instead of a Canadian bank account. In this case what Fava reports might make some sense, as by the end of the year the 1 million USD that you made as income would now be worth 1.5 million CAD. But I would argue that even in this case it should not be reported as such as the difference (0.3 million CAD) is unrealised currency gain and should be reported towards a currency gain account, and not towards the sales account which is being done right now.

I think that income and expense accounts are "realised" accounts, as in when you book an income, the amount that you make gets realised at the date of the transaction. And that for these accounts any currency conversion must be carried out according to the rates applicable for the date of the transaction, and not the current date or the last date of the interval. I think that asset accounts and income/expense accounts are fundamentally different in this way.

**Comment by molikto** [comment] 2020-05-15 06:59
maybe for "market value" and "currency" conversions, an option to say when the conversion happens should be given, and a user can select "at posting time", "at aggreation end" (for bar charts), "at the end of the reporting period (not know if this is useful?)

**Comment by yagebu** [comment] 2020-05-15 16:11
@jitinl: In Beancount, prices aren't kept around after the transaction - so to keep track of the cost basis, you'll need to use the cost syntax (see the [Beancount language syntax documentation](https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit#heading=h.mtqrwt24wnzs))

> maybe for "market value" and "currency" conversions, an option to say when the conversion happens should be given, and a user can select "at posting time", "at aggreation end" (for bar charts), "at the end of the reporting period (not know if this is useful?)

Allowing a date to be specified to be used for the conversions is tracked in #1048 (the examples you give are basically the default right now, when a date can be inferred, we use that).

**Comment by jitinl** [comment] 2020-05-15 17:01
@yagebu consider the following file:

```
2014-01-01	 open Income:Sales
2014-01-01	 open Equity:Drawings 
2014-01-01   open Expenses:Banking:Charges 


2017-04-01 price USD 1.1 CAD
2017-04-03 price USD 1.2 CAD
2017-04-03	* "Transaction"
    Income:Sales                -10 USD @       1.2 CAD
    Equity:Drawings     10 CAD
    Expenses:Banking:Charges

2017-04-20 price USD 1.4 CAD
2020-01-01 price USD 1.5 CAD
```

Fava shows this report:

![image](https://user-images.githubusercontent.com/5412842/82076318-4eba2080-96fb-11ea-9a65-aaa912281ec4.png)


Is this the expected behaviour? It somehow seems very wrong to me.

In my opinion, the chart does the right thing by converting at the date of the transaction. In terms of bean-query, it is doing something like `convert(position,"CAD",date)`. Whereas the tabular report, I think does the wrong thing by using the latest conversion value - something like `select convert(position, "CAD")`. In my understanding the price at the date of transaction should be used here, like it's being used in the chart. Or like @molikto suggested, there could be an option to choose the conversion to take place "at the posting date". Because the income I made at a particular date should be a function of the exchange rate on that day, not of today's exchange rate. It doesn't make sense to me. But maybe I am misunderstanding something?

**Comment by yagebu** [comment] 2020-05-15 18:06
> Is this the expected behaviour?

Yes - the conversions happen after aggregation. To me, it seems more consistent that way.

> In my opinion, the chart does the right thing by converting at the date of the transaction.

It converts at the end of the interval, which just happens to be the date of the transaction in this case, so that's accidental.

> I did not use the cost syntax because the documentation says it's not a good idea to use costs for currency conversions and the price syntax should be used.

From your comment above it seemed like you actually want to keep track of currency conversion gains, in which case you should use the cost syntax.

**Comment by jitinl** [comment] 2020-05-15 18:18
Okay, I understand your perspective. Although I still think this behaviour definitely seems misleading, at least to me. But thanks for putting out your time on this! :)

One last comment, if the chart is picking up at the end of the interval, should it not have used the 2017-04-20 price value I added? I added it specifically to check if it was picking at the end of the interval, or at the transaction date.

**Comment by yagebu** [comment] 2020-05-15 20:08
I think all conversions of income and expenses will be "wrong" in some way. I think that's due to the conversion just being less well-defined in comparison to, say, assets. You might actually convert an asset to another currency, whereas your 10 USD of income will always just be 10 USD of income and any conversion will only be an approximation.

Let's say you have three transactions of 10 USD each on the same day, two of them to your bank account with different conversion rates and the other one in cash (which you pay into your bank account a few days later). We'd have different options to convert that could all be considered "correct": We could use the mid-market rate of that day for all conversions to CAD; we could use the actual rates for the first two and the mid-market rate for the third; we could use the actual rate for the first two and for the third one the rate when we it into our account. And now spread that to 365 days with all different rates, then I think there's no right way to do the conversion to CAD. But I can aggregate it to 10965 USD and convert that at one chosen rate.

The recommendation to not use the cost syntax for currency conversions is just that - a recommendation. If you want to track the cost basis of currencies, just use it :) If you view your 10 USD of income not as just 10 USD but 10 USD that got converted to 12 CAD, then using cost notation seems to be the right tool and the conversion is well-defined and will always start with 12 CAD. Or if you don't actually care about the fact that it was 10 USD in the first place, don't enter that information into your Beancount file. So I think Beancount let's you choose from "I just know one currency", "Currency conversions might get messy, let's not bother with that too much, tracking my investments is complex enough", or "I need to track all the currencies in full detail".

> One last comment, if the chart is picking up at the end of the interval, should it not have used the 2017-04-20 price value I added?

If no time filter is set, the first and last transaction are used as start and end dates for these charts and alignment to interval ends is not ensured.

**Closed** 2020-05-15 21:02 UTC
Labels: bug

**Comment by jitinl** [comment] 2020-05-15 21:46
I understand that it's a conscious design decision that you have made to do it this way, and it is a very subjective thing, so there's no right or wrong. It is just what you choose to show in the report. 

For my purpose, the reason why I was not using cost basis was that the documentation so strongly asserted against using cost basis for currencies. But I guess in the case of income accounts it makes sense to use them this way.

Thanks a lot for spending time discussing this and your help with this! :)
