### ISSUE TITLE
Saved BQL Queries do not run anymore

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#1014] opened 2019-11-19 08:16 UTC
I have 3 queries saved, and I can see them under 'Query' in the left-hand-side bar.

Clicking any of the 3 brings up the /query/ page. The general page, it does not actually run the query or display results (which was the previous behaviour in 1.8 at least, I just jumped to 1.11).

I CAN click/type 'run <queryname>' in the query page and it'll run, but this is an additional step which was not previously required (and current behaviour seems to defeat the purpose of having these things in the left-hand-side bar.

**Comment by yagebu** [comment] 2019-11-19 20:10
Yeah, that sounds like a bug, probably the URL query string gets stripped somewhere - for the other sidebar links we need to update the query string to match the filters.

**Comment by yagebu** [comment] 2019-11-22 17:24
Actually, this is a duplicate of #958 and was fixed

**Closed by yagebu** 2019-11-22 17:24 UTC
Labels: bug, duplicate
