### ISSUE TITLE
Fava editor cannot save Beancount file changes

### ISSUE THREAD

**Issue by Tianci278** [beancount/fava#1234] opened 2021-02-19 07:46 UTC
Sometimes when I edit my Beacount on Fava editor, the editor will randomly lose its save function. When it happens, the save button is turned grey, and when pressing Ctrl+S the editor says "Error: Trying to read a non-source file".

**Comment by yagebu** [comment] 2021-02-21 15:29
Which version of Fava are you using and which operating system are you on? In which browser does this happen? Does it only happen with some specific filenames and do they include unicode characters?

**Comment by Tianci278** [comment] 2021-02-22 13:00
> Which version of Fava are you using and which operating system are you on? In which browser does this happen? Does it only happen with some specific filenames and do they include unicode characters?

Sorry, I should have mentioned them.
This has happened twice on my windows computer with chrome browser, file name & path are all English letters.  Not sure which version of fava it is, but should be the latest (19 Feb 2021) version on pypi (I installed it via pip). 

It is strenge, because it usually works just fine before it suddenly loses the save function on the very same file.

I will bring more details when it happens again.

**Comment by yagebu** [comment] 2021-04-18 09:35
I'll close this issue since it's not really reproducible, if it happens again, just comment.

**Closed by yagebu** 2021-04-18 09:35 UTC
Labels: bug, status:not-reproducible
