### ISSUE TITLE
fava jinja_options key error

### ISSUE THREAD

**Issue by scanta2** [beancount/fava#1295] opened 2021-06-14 18:58 UTC
While I can build and install fava on Fedora 35, it fails to run with the following call stack (python 3.10b2):
```
(finance) [stefano@localhost beancount_ledger] $ Traceback (most recent call last):
  File "/home/stefano/venv/finance/bin/fava", line 33, in <module>
    sys.exit(load_entry_point('fava', 'console_scripts', 'fava')())
  File "/home/stefano/venv/finance/bin/fava", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/stefano/git_repos/fava/src/fava/cli.py", line 11, in <module>
    from fava.application import app
  File "/home/stefano/git_repos/fava/src/fava/application.py", line 67, in <module>
    app.jinja_options["extensions"].append("jinja2.ext.do")
KeyError: 'extensions'
```

**Comment by Tarliton** [comment] 2021-06-17 01:26
It's because of Flask version >= 2.0.0, it requires[ jinja2 version > 3.0.](https://github.com/pallets/flask/blob/main/setup.py#L8).

We would need to update Fava to work with Flask 2.0 to fix this.

**Comment by yagebu** [comment] 2021-06-29 15:20
This is a duplicate of #1266 and was fixed quite some time ago in https://github.com/beancount/fava/commit/e004182f07923c43e07e10e1dfc0e9363d1f0e4c (which was part of v1.19 in May)

**Closed by yagebu** 2021-06-29 15:20 UTC
