### ISSUE TITLE
Filters: Excluding transactions involving an account.

### ISSUE THREAD

**Issue by seltzered** [beancount/fava#768] opened 2018-05-20 06:48 UTC
One way I'm trying to use fava is to exclude certain accounts (e.g. seeing a personal balance sheet with work-related 'expense' and reimbursement 'income' accounts hidden), and after the advice in [759](https://github.com/beancount/fava/issues/759) I'm trying to understand fava's filters before thinking about adding extensions for custom reports.

An initial approach was to leverage the regex feature of AccountFilter to just do a negative lookaround expression on account. Using [long-example.beancount](https://raw.githubusercontent.com/beancount/fava/master/tests/data/long-example.beancount), an expression such as `(?!^.*Food:Alcohol)(^.*)` will strip out 

`1980-05-12 open Expenses:Food:Alcohol` but not 
```
2015-02-01 * "Another Sports Pub" "" #trip-chicago-2015
  Liabilities:US:Chase:Slate                       -12.02 USD
  Expenses:Food:Alcohol                             12.02 USD
```
This is because in filter.py's `entry_account_predicate` returns 
'True if predicate is True for *any* account of the entry.' which works for normal filtering but in the case of exclusions it should be ''True if predicate is True for *all* accounts of the entry.'

So I'm trying to think about the best way to improve filters.py for this purpose. At the function call level, one way would be to add an option to AccountFilter to switch between ORing/ANDing. But the question still remains of how the user would express this option within the query string.

Another thought is to modify AdvancedFilter to handle posting-level data (account, units, ...) since it already has a convention that allows for optional exclusion (-) outside the query string itself, so in our example it'd look like `-Account:"Expenses:Food:Alcohol"`, and support regexes so  `-Account:"*:Food:Alcohol"` would also work.

**Comment by yagebu** [comment] 2018-06-24 20:29
> Another thought is to modify AdvancedFilter to handle posting-level data (account, units, ...) 

The advanced filter already supports accessing posting-level data, so far only with a `any()` function (matching all entries where at least one posting satisfies the filter). I've added a `all()` function, which should work for your usecase.

**Comment by yagebu** [comment] 2018-06-26 15:19
I think this is now possible, so I'll close the issue. @seltzered: If this doesn't work for you, feel free to reopen :)

**Comment by seltzered** [comment] 2018-06-26 15:20
Thanks! I'll try it out soon.

**Closed by yagebu** 2018-06-26 15:19 UTC
Labels: enhancement

**Comment by victoraraujo01** [comment] 2018-07-07 16:40
@yagebu, this is still not available on the stable build, right? I also tried it on the [dev-demo](https://favadev.pythonanywhere.com/example-with-budgets/income_statement/) but it still isn't available.

I cloned the repository and installed the development version and it, indeed, works. However, the filter is not applied by pressing enter on the field, it only works if you type it and change sections using the sidebar (from income statement to balance sheet, for example). Is this how it's supposed to work? I was a little confused by this behaviour and actually thought it wasn't working before trying to switch sections.

**Comment by yagebu** [comment] 2018-07-09 20:31
> this is still not available on the stable build, right?

Right. I'm trying to make a new release soon though

> I also tried it on the dev-demo but it still isn't available.

It should work now (on the free tier of pythonanywhere.com, the cron jobs expire from time to time, so it doesn't always get updated)

> I cloned the repository and installed the development version and it, indeed, works. However, the filter is not applied by pressing enter on the field, it only works if you type it and change sections using the sidebar (from income statement to balance sheet, for example). Is this how it's supposed to work? I was a little confused by this behaviour and actually thought it wasn't working before trying to switch sections.

That sounds odd (and I can't really reproduce it)

**Comment by seltzered** [comment] 2018-07-09 21:01
Yeah, it does seem to work on the dev demo - here's an [example](https://favadev.pythonanywhere.com/example-beancount-file/income_statement/?filter=all%28-account%3A%22Expenses%3AFood%3AAlcohol%22%29 ) of filtering out alcohol expenses. Regarding the filter entry field, it does seem to require either hitting the 'enter' key or switching sections (i.e. it doesn't function as an 'instant' search, which seems reasonable though).

**Comment by victoraraujo01** [comment] 2018-07-10 02:51
> That sounds odd (and I can't really reproduce it)
I just tested it on Chrome on my Mac and it works as intended (pressing 'enter' triggers the filter). However, on Safari pressing 'enter' does not trigger the filter, neither on the Mac nor on iOS...
