### ISSUE TITLE
hope to support 'other' currency again

### ISSUE THREAD

**Issue by skyue** [beancount/fava#1133] opened 2020-08-07 14:58 UTC
<img width="1250" alt="Snipaste_2020-08-07_22-53-03" src="https://user-images.githubusercontent.com/10450242/89658259-e5fcd180-d900-11ea-905d-5d3af99a8381.png">

there is a column name 'other' currency in the sheet in fava 1.10, but it miss in 1.15. 
i think it's good feature, can you support it again.

**Comment by yagebu** [comment] 2020-08-09 12:16
Duplicate of #1131

**Closed by yagebu** 2020-08-09 12:16 UTC
Labels: duplicate
