### ISSUE TITLE
drag & drop documents to the import directory

### ISSUE THREAD

**Issue by grostim** [beancount/fava#1054] opened 2020-02-13 11:56 UTC
Hi!

We can drag&drop document to attach them to any transaction or account, and this is a really nice feature.
It would be good to have an option to drag&drop a document to the import-dir in order to make them available for my importer.
Is there a way to make that possible ?

**Comment by yagebu** [comment] 2020-02-14 15:38
Duplicate of #904.

**Closed by yagebu** 2020-02-14 15:38 UTC
