### ISSUE TITLE
Prices are not transitive (should they be?)

### ISSUE THREAD

**Issue by MarkusTeufelberger** [beancount/fava#647] opened 2018-01-23 23:06 UTC
Consider the following file:

````
2000-01-01 open Assets:Time
2000-01-01 open Equity:Time

2000-01-01 commodity HOUR
2000-01-01 commodity MIN
2000-01-01 commodity SEC

2000-01-01 price HOUR 60 MIN
2000-01-01 price MIN 60 SEC

option "operating_currency" "SEC"

2000-01-01 * "get 24 hours"
  Assets:Time  24 HOUR
  Equity:Time
````

If I select "converted to SEC" in the interface, I'd expect to see 86400 SEC in the UI, since there is a price for HOUR to MIN and a price for MIN to SEC.

If I add the line `2000-01-01 price HOUR 3600 SEC`, everything works out as expected.

BUT:

While time has a strict and fixed conversion rate, many real world prices are not totally frictionless during conversion. There also might be the problem that for longer conversion chains 2 different prices could be calculated (e.g. I have EURUSD and EURGBP prices as well as USDJPY and GBPJPY prices - if I want to know how much some Yen are in Euro, it probably will give slightly different results going through USD or GBP).

At least for cases like the example where only a single path through currencies is possible, it should at least be an option to directly convert, in other cases it might be worth having a plugin that allows selecting strategies (always pick the highest/lowest price) or paths (always route through USD if possible).

Another difficulty (as if this isn't hard enough) is that prices are often not available for every day, even for huge Forex markets like EURUSD because the currency pairs are not traded 24/7. This makes it difficult to know the exact EUR price of a good that is priced in USD if you bought it on a weekend (whould you linearly interpolate the price between Friday and Monday, should you always take the Friday value as the latest known information at that time, should you take the nearest day with a known price...).
A typical example for this are various cryptocurrencies which are sometimes only priced/traded against Bitcoin which in turn is mainly traded in/against USD, so it is often the case that a local currency is 2-3 hops removed from any actually existing price source.

Anyways: It would be nice to have a way (even with caveats, warning signs and some explicit options) to enable transitive prices.

**Comment by yagebu** [comment] 2018-02-02 12:56
This is a duplicate of #587, also see my comment there.

You're mentioning a few points why this is not trivial to do in a naive way. Also, from the performance perspective, it's good that fetching a price is just a simple list lookup and not a list lookup combined with a graph search. I think it would be best to specify explicitly all desired conversion routes. It shouldn't be hard to write a plugin that adds all prices for these given conversion routes (and this plugin could be hosted at https://github.com/beancount/fava-plugins).

**Closed** 2018-02-21 00:29 UTC
Labels: duplicate, question
