### ISSUE TITLE
decimal in query with fava differents from bean-query

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#1249] opened 2021-04-07 21:19 UTC
if i run a query in fava, i will see the number with a number of decimal (only two decimal) different than if i run the same query in bean-query ( more decimals) .
could it be possible to have the same rendering in fava ?
query:
SELECT account, units(sum(position)) AS quantity
WHERE account ~ "Generation"
GROUP BY account 
ORDER BY account
in fava : 
account | quantity
Assets:Titre:Assurance-vie | 461.99 fonda   1.53 fondb   16.64 fondc  102.67 fondd   6.32 fonde
Assets:Titre:Assurance:Cash | 200.00 EUR

in beanquery:
         account                         quantity
Assets:Titre:Assurance-vie      461.990 fonda   ,   6.3159880 fonde     , 102.6742290 fondd   ,   1.5304550 fondb       ,  16.6438190 fondc
Assets:Titre:Assurance-vie:Cash 200.00      EUR

**Comment by yagebu** [comment] 2021-05-16 09:42
I can't reproduce this. On the holdings report, the number of displayed digits matches the display context. Which version of Fava are you running, can you check if this is fixed in the latest development release for you? If not, can you provide an example file that let's me reproduce this problem?

**Closed** 2021-08-28 09:56 UTC
Labels: status:not-reproducible
