### ISSUE TITLE
Regression: Number of displayed decimals different between 1.26.1 and 1.25

### ISSUE THREAD

**Issue by vishalg** [beancount/fava#1706] opened 2023-10-31 07:39 UTC
Between 1.26.1 (docker latest) and 1.25 (docker v1.25) the display has changed for the situation where "Converted go XXX" option is selected. While some account balances are displayed to 3 decimals others are only up to 2 decimal places. For some reason "Converted to USD" displays with 4 decimal places in both the versions.

 e.g 1.26.1
![image](https://github.com/beancount/fava/assets/191732/1acef116-81b3-4923-b7d5-c5a29ec9a358)
![image](https://github.com/beancount/fava/assets/191732/0fd775d7-0cae-4bae-a7ef-bb5cd7fc1fd8)

and 1.25
![image](https://github.com/beancount/fava/assets/191732/3486c37d-fcbe-4d80-9ac3-d521a170f575)
![image](https://github.com/beancount/fava/assets/191732/dbb52c05-eb1c-42a5-a6fb-30e1a7573515)

**Comment by yagebu** [comment] 2023-11-11 10:56
I believe this is a duplicate of #1696

**Closed by yagebu** 2023-11-11 10:56 UTC
