### ISSUE TITLE
Latest fava tries to use http for api requests when served over https with a reverse proxy

### ISSUE THREAD

**Issue by tarioch** [beancount/fava#1064] opened 2020-02-21 21:33 UTC
My setup uses a reverse proxy which does the https and fava itself is running on simply http (I use kubernetes for doing all of that).

This uses to work fine with 1.12 but since I upgraded to 1.14 it tries to access the api through http instead of https urls. (for things like imports or api/changed)

Is there a way I can force to use https for the api somehow?

**Comment by tarioch** [comment] 2020-02-21 22:18
I think I figured something a bit more out, it looks like it starts with a request to '/beancount/api/changed' as there is a trailing '/' missing this then get's redirected to 'http://mydomain/beancount/api/changed/' and then the browser prohibits executing this.

**Comment by yagebu** [comment] 2020-02-22 10:44
This is a duplicate of #1027.

This is also a deployment issue - Fava should expect redirects to work, so this might break your instance of Fava in other cases. So figuring out how to fix that in your setup would probably be a worthwhile investigation.

But in any case, we can also use the correct URLs :) Though I would go the other way and use unique ones without the trailing slashes (see https://flask.palletsprojects.com/en/1.1.x/quickstart/#unique-urls-redirection-behavior, https://blog.restcase.com/7-rules-for-rest-api-uri-design/)

**Closed by yagebu** 2020-02-22 10:44 UTC
