### ISSUE TITLE
Error edit last entry in Journal

### ISSUE THREAD

**Issue by uzkikh** [beancount/fava#576] opened 2017-08-09 08:23 UTC
Clicking on the entry date (that have last note in my .beancount file) in the Journal will open an overlay that shows the error: 
_The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application._

**Comment by yagebu** [comment] 2017-08-16 16:53
Hey, thanks for the report. Can you try running Fava in debug mode (by starting it with the `--debug` command line flag) to see if it produces a more detailed error message? Also, can you provide a minimal beancount file with which you can reproduce this?

**Comment by yagebu** [comment] 2017-09-18 14:41
Closing, as I can't reproduce it without anything to go on...

**Closed by yagebu** 2017-09-18 14:41 UTC
Labels: bug, status:not-reproducible
