### ISSUE TITLE
Closed accounts are showing

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#783] opened 2018-06-29 22:43 UTC
I just realized this, not sure whether/what has changed. It defaults to "show-closed-accounts" being False (and I can see that in my options) but my old accounts from 5+ years ago are suddenly showing up.

**Comment by yagebu** [comment] 2018-07-02 10:47
I can't reproduce this - can you provide some example?

**Comment by ngoonee** [comment] 2018-07-04 06:43
Well, it shows up with this minimal example:-

    ;; -*- mode: org; mode: beancount; -*-
    * Options
    option "operating_currency" "MYR"
    plugin "beancount.plugins.auto_accounts"
    
    2014-07-30 open  Assets:Banking:Bank:Type MYR
    2014-07-31 * "hi"
        Assets:Banking:Bank:Type 10.00 MYR
        Assets:Cash:Out
    2014-12-31 close Assets:Banking:Bank:Type

Under 'Balance Sheet' the account still shows even though it's closed. After a bit of testing, if I balance the account out to 0 then it works. So this only applies to accounts which have been both closed and still have some balance remaining.

**Comment by yagebu** [comment] 2018-07-04 08:43
Accounts with a balance that is not zero should always be shown.

I'm a bit surprised that closing a non-empty account isn't an error - @blais is this intentional?

**Closed by yagebu** 2018-07-04 08:43 UTC

**Comment by ngoonee** [comment] 2018-07-05 00:48
I see, understood. I see the logic of that, but in fact most of my legacy bank accounts do close with some amount inside (minimal) due to some crazy regulations which charge X for closing accounts but allow accounts to have a minimal balance of less than X (which would then be dormant for 7 years until mandatory closure).
