### ISSUE TITLE
Rendering account trees in Fava 1.25+

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1721] opened 2023-12-14 06:38 UTC
[Fava Investor](https://github.com/redstreet/fava_investor)'s asset allocation page looked [like this](http://favainvestor.pythonanywhere.com/example-beancount-file/extension/Investor/?module=aa_class). To accommodate the changes in Fava 1.25 onwards, I tried to make [these changes](https://github.com/redstreet/fava_investor/commit/79a10f437ea40b4a3f35f49fc18229031c5d6e09#diff-e91c9f9f3da29c772c933154ec2f541b6055019570c8bf98891c160b2c388ea6). However, this is the result:

**Old:**
![image](https://github.com/beancount/fava/assets/691755/98b18a01-755e-4856-88fc-eaf25872ec84)

**New:**
![image](https://github.com/beancount/fava/assets/691755/d7d6c736-119c-45b0-b6f6-010e25bb456d)

If you or anybody could provide guidance, tips, or pointers on how to approach changing the [Investor.html](https://github.com/redstreet/fava_investor/blob/main/fava_investor/templates/Investor.html) code based on Fava's changes in this area, it would be most appreciated. Thank you!

**Comment by iamkroot** [comment] 2023-12-27 16:43
Also hit this when using tree table. 

From what I can tell, the `<tree-table>` tag is no longer valid, and we need to do something like this (use `tree-table` inside templates)

https://github.com/beancount/fava/blob/31220467a047b9c55e38061267fe71a37ecb0904/src/fava/templates/balance_sheet.html#L3-L29

**Comment by yagebu** [comment] 2024-01-06 14:49
Thanks for reporting this - this is also basically a duplicate of #1721, so I'll close this one here - I'll re-add the now unused CSS and JS so that extensions like fava_investor can work unchanged for now. Let's track how extensions could use the "new" tree tables in the other issue.

**Closed by yagebu** 2024-01-06 14:49 UTC
Labels: duplicate, extension

**Comment by redstreet** [comment] 2024-01-06 20:58
Sounds great, thanks much @yagebu!
