### ISSUE TITLE
Struggling with multi-currency details

### ISSUE THREAD

**Issue by wyfiwyfi** [beancount/fava#982] opened 2019-10-06 16:08 UTC
I'm relatively new to Fava and, despite having read the manuals and seeking out examples, I'm struggling to understand how certain multi-currency transactions should be input to produce useful results. Fava's income statement, balance sheet and associated graphs are also not producing the informative results I would expect. It seems I'm missing some basic principles or rules of thumb. I'd appreciate any pointers .

My operating currencies are EUR and DKK. As an example, take this single transaction from my bank statement: 

<img width="762" alt="Screenshot 2019-10-06 at 16 23 07" src="https://user-images.githubusercontent.com/40526228/66271514-b4395b00-e856-11e9-869b-a75a7a9c1ebc.png">

It balances, but on the Fava income statement, the amount for Expenses:Communciation:Services is missing. I would expect this to be in EUR, or even a column in USD, but it is just not present. 

<img width="648" alt="Screenshot 2019-10-06 at 16 40 32" src="https://user-images.githubusercontent.com/40526228/66272023-66275600-e85c-11e9-83ee-98d3b2960dd8.png">

 In Beancount's income statement, however, I get this:

<img width="1076" alt="Screenshot 2019-10-06 at 16 43 24" src="https://user-images.githubusercontent.com/40526228/66271655-7e957180-e858-11e9-97ce-65bc94fb71dd.png">

Again, I would expect this to be in EUR, an operating currency, inasmuch as the exact amount in EUR is provided. At least the amount appears in the report, however, even if not in an operating currency, as anticipated.

I've also attempted entries like these with much the same result:
<img width="701" alt="Screenshot 2019-10-06 at 17 27 13" src="https://user-images.githubusercontent.com/40526228/66272209-c0c1b180-e85e-11e9-8bec-46684fbfa565.png">
<img width="726" alt="Screenshot 2019-10-06 at 17 27 31" src="https://user-images.githubusercontent.com/40526228/66272213-c6b79280-e85e-11e9-9292-f12bec71d2c6.png">

Finally, can someone explain the how the drop-down "Convert to XXX" options are supposed to work? When I change it seems to have no or little effect. Are these only supposed to change the graph and not the tables on the page? Is there a way to view an income statement and balance sheet converted to a single currency (providing the relevant prices are given, of course)?

Thanks for any help and pointers.

**Comment by yagebu** [comment] 2019-10-08 19:51
I can't reproduce this with an example transaction like the one you offered. For the following example,  three columns are displayed with only 18 USD in Expenses:Test on the income statement.

```
option "operating_currency" "EUR"
option "operating_currency" "DKK"

2012-12-12 * "test"
    Assets:Test -9 EUR @ 1 USD
    Assets:Test -9 DKK @ 1 USD
    Expenses:Test 18 USD
```

Can you provide a minimal example file to reproduce the issues you're witnessing?

> Again, I would expect this to be in EUR, an operating currency, inasmuch as the exact amount in EUR is provided. At least the amount appears in the report, however, even if not in an operating currency, as anticipated.

No, the Expenses:Communication:Services contains an inventory of 10 USD and should show that (unless you select a conversion and have the prices available).

> Finally, can someone explain the how the drop-down "Convert to XXX" options are supposed to work? When I change it seems to have no or little effect. Are these only supposed to change the graph and not the tables on the page?

They'll have the effect that in most places, currencies are converted to the selected one, if the prices are available. I assume your input file does not have any prices (you can see the prices on the commodities page).

> Is there a way to view an income statement and balance sheet converted to a single currency (providing the relevant prices are given, of course)?

Yes, the "Convert to XXX" options.

**Comment by yagebu** [comment] 2019-11-22 17:19
Closing this as I can't reproduce the apparent bug that you're seeing, and I hopefully answered your questions - feel free to reopen of course :)

**Closed** 2019-11-22 17:19 UTC
Labels: question, status:not-reproducible
