### ISSUE TITLE
macOS Safari: Can't expand/collapse balance hierarchy

### ISSUE THREAD

**Issue by mhansen** [beancount/fava#1206] opened 2021-01-04 01:28 UTC
Expected: click an arrow next to a balance, it should expand/collapse the hierarchy.

Actual: Clicking these little arrows does nothing in Safari:

![image](https://user-images.githubusercontent.com/105529/103493950-6f043e80-4e88-11eb-9905-889414d0019d.png)

Safari Version 14.0.2 (16610.3.7.1.9)

```
$ fava --version
fava, version 1.17
```

Works fine in
- Firefox for macOS 78.0.2 (64-bit)
- Chrome for macOS `Version 87.0.4280.88 (Official Build) (x86_64)`

the sections expand and collapse

**Comment by yagebu** [comment] 2021-01-04 15:38
Duplicate of #1169, see #1180

**Closed by yagebu** 2021-01-04 15:38 UTC

**Comment by mhansen** [comment] 2021-01-04 21:16
Thank you!
