### ISSUE TITLE
Price conversion not applied in single/accumulated account view

### ISSUE THREAD

**Issue by MarkusTeufelberger** [beancount/fava#662] opened 2018-02-05 10:07 UTC
For example on this page:

https://fava.pythonanywhere.com/example-beancount-file/account/Income:US:Hoogle/

(an additional problem for that demo file is that there is no VACHR <--> USD price defined in the source file, so the conversion can't work there, this is just to illustrate which report I mean)

If prices for pricing VACHR in USD were available, I would expect to see a single line denominated in USD in the graph if I select "Converted to USD" from the dropdown. Currently this is not the case (even with the prices available).

**Comment by tbm** [comment] 2018-02-05 12:18
This relates to #659

**Comment by yagebu** [comment] 2018-02-05 14:36
I'm closing this as a duplicate of #659, thanks for the report!

**Closed by yagebu** 2018-02-05 14:36 UTC
