### ISSUE TITLE
Charts and menus not showing up in fava 1.25

### ISSUE THREAD

**Issue by dousha** [beancount/fava#1653] opened 2023-08-02 03:33 UTC
The browser (both Firefox 115.0.3 and Edge 115.0.1901.188) refuses to load `app.js` with the following error message showing up in the console:

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

I tried reinstalling fava using `pip` but the problem persists. There is no reverse proxy in place -- the URL I used to access fava is `http://127.0.0.1:5000`. The operating system I use is Windows 10 22H2.

What should I do to further investigate?

**Comment by yagebu** [comment] 2023-08-02 16:19
I'd assume that this is a duplicate of https://github.com/beancount/fava/issues/1653 - see that issue on how to fix your registry.

**Closed** 2023-09-09 12:34 UTC
Labels: duplicate, platform:windows, bug-external
