### ISSUE TITLE
Issue on installing fava on a VPS

### ISSUE THREAD

**Issue by Takounie** [beancount/fava#1057] opened 2020-02-15 21:17 UTC
Hello all,

When I try to install fava on my vps (Ubuntu 18 or Debian 10) i get the following message when calling "fava" command.
```
Traceback (most recent call last):
  File "/usr/local/bin/fava", line 6, in <module>
    from fava.cli import main
  File "/usr/local/lib/python3.7/dist-packages/fava/cli.py", line 7, in <module>
    from werkzeug.contrib.profiler import ProfilerMiddleware
ModuleNotFoundError: No module named 'werkzeug.contrib'
```
Anyona has any ideo on how to fix that please?

Thanks.

**Comment by yagebu** [comment] 2020-02-16 11:58
Duplicate of #1052

**Closed by yagebu** 2020-02-16 11:58 UTC
