### ISSUE TITLE
Sub-account folding arrows not working in Safari

### ISSUE THREAD

**Issue by epmoyer** [beancount/fava#1180] opened 2020-11-15 15:54 UTC
OS: macOS Catalina 10.15.7
Safari: Version 14.0 (15610.1.28.1.9, 15610)
Fava: 1.17

- The clickable triangles used to fold (expand/collapse) sub-accounts are unresponsive in Safari 14.0 on Catalina 10.15.7.
- Works in Firefox and Chrome (tested on MacOS)
- Existed in Fava 1.16.  I upgraded to 1.17 to see if it would fix the problem but it didn't.
- Nothing gets logged in the javascript console. I haven't attempted any debug, but at the very least it doesn't appear to be throwing an exception or logging an error.

**Comment by yagebu** [comment] 2020-11-15 16:10
This is basically a duplicate of #1169.

**Comment by epmoyer** [comment] 2020-11-15 23:28
Ah! Apologies for the duplication; I missed it in my initial search because it was closed. Cheers!

**Comment by vloris** [comment] 2020-11-17 14:55
I don't think this is a duplicate of #1169, I just updated to the last commit on master and the folding arrows still don't work. The ".." buttons as mentioned in the other ticket _do_ work now.

**Comment by yagebu** [comment] 2020-11-22 19:49
> So I guess this is not supposed to have been fixed yet?

No, sorry I should have elaborated a bit what I meant by "this is basically a duplicate". Ideally this would be fixed by Safari simply implementing the spec, but since I don't know when that will happen, I'll add another workaround for the tree tables.

**Comment by vloris** [comment] 2020-11-25 08:54
Thanks, that commit has indeed fixed the tree-table folding issue!

**Closed** 2020-12-19 14:54 UTC
Labels: duplicate
