### ISSUE TITLE
file type png(jpg/html) is not implemented

### ISSUE THREAD

**Issue by ouyanmao** [beancount/fava#1254] opened 2021-04-17 02:05 UTC
After version 1.16, Documents can only preview pdf, but cannot preview .jpg .png .html normally, prompting "Preview for file /Path/FileName.png with file type png is not implemented"

**Comment by yagebu** [comment] 2021-04-17 14:35
Duplicate of #1253

**Closed by yagebu** 2021-04-17 14:35 UTC
